name: "Terraform Validate"
description: A composite GitHub Action to check formatting and validate Terraform configuration.

inputs:
  working-directory:
    description: Directory containing Terraform code
    required: false
    default: "."
  soft-fail:
    description: Continue workflow even if validation fails
    required: false
    default: "false"

outputs:
  valid:
    description: "true if validation passed, false if failed"

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -input=false
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}

    - name: Terraform FMT Check
      id: fmt
      run: |
        set -e
        if terraform fmt -check -recursive; then
          echo "✅ Terraform FMT check passed"
          echo "### ✅ Terraform FMT check passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Terraform code is not properly formatted"
          echo "### ❌ Terraform FMT check failed" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ inputs.soft-fail }}" == "true" ]]; then
            echo "::warning::Terraform FMT failed (soft fail enabled)"
          else
            exit 1
          fi
        fi
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}

    - name: Terraform Validate
      id: validate
      run: |
        set -e
        if terraform validate -no-color; then
          echo "✅ Terraform validation passed"
          echo "### ✅ Terraform validation passed" >> $GITHUB_STEP_SUMMARY
          echo "valid=true" >> $GITHUB_OUTPUT
        else
          echo "❌ Terraform validation failed"
          echo "### ❌ Terraform validation failed" >> $GITHUB_STEP_SUMMARY
          echo "valid=false" >> $GITHUB_OUTPUT
          if [[ "${{ inputs.soft-fail }}" == "true" ]]; then
            echo "::warning::Terraform validate failed (soft fail enabled)"
          else
            exit 1
          fi
        fi
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
