name: "Terraform Validation and Formatting Checks"
description: "A composite GitHub Action that performs Terraform format (fmt) and configuration validation."

inputs:
  terraform-dir:
    description: "Relative path to the directory containing Terraform configuration files (e.g., 'tf', 'infrastructure')."
    required: false
    type: string
    default: "tf"

  release-tag:
    description: "Git release tag to check out. If omitted, the latest commit on the default branch is used."
    required: false
    type: string
    default: ""

  soft-fail:
    description: "Set to 'true' to allow the workflow to continue even if Terraform format or validation fails. Use 'false' to enforce strict validation."
    required: false
    type: string
    default: "true"

outputs:
  valid:
    description: "Set to 'true' if validation passed, 'false' if it failed."

runs:
  using: "composite"
  steps:
    - name: Set Checkout Ref
      id: set-ref
      shell: bash
      run: |
        if [[ -n "${{ inputs.release-tag }}" ]]; then
          echo "ref=${{ inputs.release-tag }}" >> $GITHUB_OUTPUT
        else
          echo "ref=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        fi

    - name: Checkout Repo
      id: checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ steps.set-ref.outputs.ref }}

    - name: Setup Terraform
      id: setup-terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize Terraform
      id: terraform-init
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      run: terraform init -backend=false

    - name: Check Terraform Formatting (FMT)
      id: terraform-fmt-check
      shell: bash
      working-directory: "${{ github.workspace }}/${{ inputs.terraform-dir }}"
      run: |
        if terraform fmt -check -recursive; then
          echo "✅ Terraform FMT check passed"
          echo "### ✅ Terraform FMT check passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Terraform code is not properly formatted"
          echo "### ❌ Terraform fmt check failed" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ inputs.soft-fail }}" == "true" ]]; then
            echo "::warning::Terraform fmt check failed (soft fail enabled)"
          else
            exit 1
          fi
        fi

    - name: Validate Terraform Configuration
      id: terraform-validate
      shell: bash
      working-directory: "${{ github.workspace }}/${{ inputs.terraform-dir }}"
      run: |
        if terraform validate -no-color; then
          echo "✅ Terraform validation passed"
          echo "### ✅ Terraform validation passed" >> $GITHUB_STEP_SUMMARY
          echo "valid=true" >> $GITHUB_OUTPUT
        else
          echo "❌ Terraform validation failed"
          echo "### ❌ Terraform validation failed" >> $GITHUB_STEP_SUMMARY
          echo "valid=false" >> $GITHUB_OUTPUT
          exit 1
        fi
